<a href="https://colab.research.google.com/github/NikhilJ2712/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1 D Array
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [ ]:
arr.append(6)

In [ ]:
arr

[1, 2, 3, 4, 5, 6]

In [ ]:
# Numpy Array Formation

import numpy as np

arr = np.array(arr)
print(arr.ndim) # n Dimensions
print(arr.shape) # Dataset Shape : rows, columns
print(arr) # Print : Array

1
(6,)
[1 2 3 4 5 6]


In [ ]:
# 2 D array

arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 D array

arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
# 2 Matrix Addition
c = a + b

print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)

d = a + c

print(d)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [ ]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)

e = a + d

print(e)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
d

array([0., 0., 0.])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

f = a + e

print(f)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [ ]:
e

array([1., 1., 1.])