<a href="https://colab.research.google.com/github/NikhilJ2712/Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1 D Array
arr = [1,2,3,4,5]
print(type(arr))

<class 'list'>


In [2]:
arr.append(6)

In [3]:
arr

[1, 2, 3, 4, 5, 6]

In [4]:
# Numpy Array Formation

import numpy as np

arr = np.array(arr)
print(arr.ndim) # n Dimensions
print(arr.shape) # Dataset Shape : rows, columns
print(arr) # Print : Array

1
(6,)
[1 2 3 4 5 6]


In [5]:
# 2 D array

arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
# 3 D array

arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
# 2 Matrix Addition
c = a + b

print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)

d = a + c

print(d)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [9]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)

e = a + d

print(e)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [11]:
d

array([0., 0., 0.])

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)

f = a + e

print(f)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [13]:
e

array([1., 1., 1.])

In [14]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3, dtype=int)

f = a + e

print(f)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [15]:
e

array([1, 1, 1])

In [16]:
a



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [19]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [20]:
a * [2,3,4]

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [21]:
# Changing Dtype : Datatype

a = np.array([1,2,3],dtype = 'float')
a

array([1., 2., 3.])

In [22]:
a = np.array([0,2,3],dtype = 'bool')
a

array([False,  True,  True])

In [23]:
a = np.array([0,2,3],dtype = 'complex')
a

array([0.+0.j, 2.+0.j, 3.+0.j])

In [24]:
# Arrange Function

a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# np.arange(start,stop,step)

a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [26]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
num.reshape(2,2,5) # in 3 d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [28]:
num.reshape(2,10) # in 2 d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
num.reshape(5,4) # in 2 d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
num.reshape(2,10) # in 2 d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
num.reshape(20,1) # in 2 d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [32]:
num.reshape(2,10,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

In [33]:
np.linspace(1,10,8)


array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [34]:
a= np.linspace(0,20,10)
print(a.size)
a

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [35]:
num = np.arange(0,30)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
# m:5 :--> No.of Rows and n:6 :--> No.of Columns
arr = num.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
arr.max()

np.int64(29)

In [38]:
arr.min()

np.int64(0)

In [39]:
arr.mean()

np.float64(14.5)

In [40]:
arr.std()

np.float64(8.65544144839919)

In [41]:
arr.var()

np.float64(74.91666666666667)

In [42]:
# Aggregate Function
arr.max(),arr.min(),arr.mean(),arr.var(),arr.std()

(np.int64(29),
 np.int64(0),
 np.float64(14.5),
 np.float64(74.91666666666667),
 np.float64(8.65544144839919))

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
arr.sum(axis = 1) # Row wise addition

array([ 15,  51,  87, 123, 159])

In [45]:
arr.sum(axis = 0) # Column wise addition

array([60, 65, 70, 75, 80, 85])

In [46]:
arr[1:4]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [47]:
arr[1:4,2:5]

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [48]:
a = np.arange(50,100) # 1-D
b = a.reshape(10,5)   # 2-D
print(b.ndim) # Checking Dimension : 2-D
b[1:3,1:3]

2


array([[56, 57],
       [61, 62]])

In [49]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [50]:
b[6:9,1:4]

array([[81, 82, 83],
       [86, 87, 88],
       [91, 92, 93]])

In [51]:
c = np.arange(101,131,dtype="float") # 1-D
print(c)

[101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112. 113. 114.
 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126. 127. 128.
 129. 130.]


In [52]:
d= c.reshape(5,6) # 2-D
print(d)
print(d.ndim) # Checking Dimension : 2-D

[[101. 102. 103. 104. 105. 106.]
 [107. 108. 109. 110. 111. 112.]
 [113. 114. 115. 116. 117. 118.]
 [119. 120. 121. 122. 123. 124.]
 [125. 126. 127. 128. 129. 130.]]
2


In [53]:
d[2:4,1:4]

array([[114., 115., 116.],
       [120., 121., 122.]])

In [54]:
d[3:,3:]

array([[122., 123., 124.],
       [128., 129., 130.]])

In [55]:
array = np.arange(101,131,dtype='float').reshape(5,6) # Clean Code
array[3:,3:]

array([[122., 123., 124.],
       [128., 129., 130.]])

In [56]:
array

array([[101., 102., 103., 104., 105., 106.],
       [107., 108., 109., 110., 111., 112.],
       [113., 114., 115., 116., 117., 118.],
       [119., 120., 121., 122., 123., 124.],
       [125., 126., 127., 128., 129., 130.]])

In [57]:
array.transpose()

array([[101., 107., 113., 119., 125.],
       [102., 108., 114., 120., 126.],
       [103., 109., 115., 121., 127.],
       [104., 110., 116., 122., 128.],
       [105., 111., 117., 123., 129.],
       [106., 112., 118., 124., 130.]])

In [58]:
array = np.arange(101,131,dtype='float').reshape(1,5,6) # Clean Code
array[3:,3:]

array([], shape=(0, 2, 6), dtype=float64)

In [59]:
array

array([[[101., 102., 103., 104., 105., 106.],
        [107., 108., 109., 110., 111., 112.],
        [113., 114., 115., 116., 117., 118.],
        [119., 120., 121., 122., 123., 124.],
        [125., 126., 127., 128., 129., 130.]]])

In [61]:
array = np.arange(101,131,dtype='float').reshape(5,6,) # Clean Code
array[3:,3:]

array([[122., 123., 124.],
       [128., 129., 130.]])

In [62]:
array = np.arange(101,131,dtype='float').reshape(5,6,1) # Clean Code
array[3:,3:]

array([[[122.],
        [123.],
        [124.]],

       [[128.],
        [129.],
        [130.]]])

In [63]:
array

array([[[101.],
        [102.],
        [103.],
        [104.],
        [105.],
        [106.]],

       [[107.],
        [108.],
        [109.],
        [110.],
        [111.],
        [112.]],

       [[113.],
        [114.],
        [115.],
        [116.],
        [117.],
        [118.]],

       [[119.],
        [120.],
        [121.],
        [122.],
        [123.],
        [124.]],

       [[125.],
        [126.],
        [127.],
        [128.],
        [129.],
        [130.]]])